insert into public.ld_letter_pairs (letter_a, letter_b, confusion_type, difficulty_tier) values
  ('b', 'd', 'mirror', 1),
  ('p', 'q', 'mirror', 1),
  ('b', 'p', 'rotation', 2),
  ('d', 'q', 'rotation', 2),
  ('n', 'u', 'rotation', 2),
  ('m', 'w', 'rotation', 2),
  ('m', 'n', 'visual', 3),
  ('i', 'j', 'visual', 3),
  ('f', 't', 'visual', 3),
  ('was', 'saw', 'sequence', 4),
  ('on', 'no', 'sequence', 4);

insert into public.ld_word_items (word, target_letter, position, difficulty_tier) values
  ('bat', 'b', 'initial', 1),
  ('dog', 'd', 'initial', 1),
  ('cab', 'b', 'final', 1),
  ('bed', 'd', 'final', 1),
  ('rabbit', 'b', 'medial', 2),
  ('ladder', 'd', 'medial', 2),
  ('pen', 'p', 'initial', 1),
  ('quiz', 'q', 'initial', 1),
  ('apple', 'p', 'medial', 2),
  ('nap', 'p', 'final', 1),
  ('map', 'm', 'initial', 1),
  ('win', 'w', 'initial', 1),
  ('animal', 'm', 'medial', 2),
  ('flower', 'w', 'medial', 2),
  ('jam', 'j', 'initial', 1),
  ('ink', 'i', 'initial', 1),
  ('fish', 'f', 'initial', 1),
  ('top', 't', 'initial', 1),
  ('after', 'f', 'medial', 2),
  ('water', 't', 'medial', 2);
